language: dart
dist: bionic
addons:
  apt:
    packages:
      - lib32stdc++6
install:
  - git clone https://github.com/flutter/flutter.git -b stable --depth 1 $HOME/flutter
  - export PATH=$HOME/flutter/bin:$PATH
  - flutter doctor
  - flutter --version
script:
  - make analyze
  - make test
